version: '3.8'

volumes:
  postgres_volume_chat:

services:
  pg:
    image: postgres:14-alpine3.17
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume_chat:/var/lib/postgresql/data
  