version: '3.8'

volumes:
  postgres_volume_chat_local:

services:
  pg:
    image: postgres:14-alpine3.17
    env_file:
      - local.env
    ports:
      - "54320:5432"
    volumes:
      - postgres_volume_chat_local:/var/lib/postgresql/data
  